name: Mixed inputs rocket

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment
         - dara
         - para
        
        
        
          
        
        

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
    - name: Store build timestamp
      run: echo "BUILD_TIME=$(date +'%T')" >> $GITHUB_ENV
    - name: Deploy using stored timestamp
      run: echo "Deploying at $BUILD_TIME"
    - name: Print the input tag to environment
      run: echo  The tags are ${{ github.event.inputs.environment }}
    - name: Set color
      id: color-selector
      run: echo "SELECTED_COLOR=yellow" >> "$GITHUB_OUTPUT"
    - name: Get color
      env:
        SELECTED_COL: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
      run: |
        echo "The selected color is $SELECTED_COL"
        echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"

        

